<?php
$params = $this->getParams();
?>
<!-- content -->
<div id="principal" class="container">    
    <div class="span12">
        <h3>
            Contatos!
        </h3>
        
        <p>
            Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. 
            Aliquam eget sapien sapien. Curabitur in metus urna. In hac habitasse platea dictumst. 
            Phasellus eu sem sapien, sed vestibulum velit. Nam purus nibh, lacinia non faucibus et, 
            pharetra in dolor. Sed iaculis posuere diam ut cursus. 
            <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet,
                metus nunc consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna,
                vulputate nec bibendum nec, posuere nec lacus. 
                <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. 
                    Nulla euismod ultrices massa, et feugiat ipsum consequat eu.</small>
        </p>
        <br />
            <select class="easyui-combobox" name="state" style="width:200px;">
                <option value="AL">Alabama</option>
                <option value="AK">Alaska</option>
                <option value="AZ">Arizona</option>
                <option value="AR">Arkansas</option>
                <option value="CA">California</option>
                <option value="CO">Colorado</option>
                <option value="CT">Connecticut</option>
                <option value="DE">Delaware</option>
                <option value="FL">Florida</option>
                <option value="GA">Georgia</option>
                <option value="HI">Hawaii</option>
                <option value="ID">Idaho</option>
                <option value="IL">Illinois</option>
                <option value="IN">Indiana</option>
                <option value="IA">Iowa</option>
                <option value="KS">Kansas</option>
                <option value="KY">Kentucky</option>
                <option value="LA">Louisiana</option>
                <option value="ME">Maine</option>
                <option value="MD">Maryland</option>
                <option value="MA">Massachusetts</option>
                <option value="MI">Michigan</option>
                <option value="MN">Minnesota</option>
                <option value="MS">Mississippi</option>
                <option value="MO">Missouri</option>
                <option value="MT">Montana</option>
                <option value="NE">Nebraska</option>
                <option value="NV">Nevada</option>
                <option value="NH">New Hampshire</option>
                <option value="NJ">New Jersey</option>
                <option value="NM">New Mexico</option>
                <option value="NY">New York</option>
                <option value="NC">North Carolina</option>
                <option value="ND">North Dakota</option>
                <option value="OH" selected>Ohio</option>
                <option value="OK">Oklahoma</option>
                <option value="OR">Oregon</option>
                <option value="PA">Pennsylvania</option>
                <option value="RI">Rhode Island</option>
                <option value="SC">South Carolina</option>
                <option value="SD">South Dakota</option>
                <option value="TN">Tennessee</option>
                <option value="TX">Texas</option>
                <option value="UT">Utah</option>
                <option value="VT">Vermont</option>
                <option value="VA">Virginia</option>
                <option value="WA">Washington</option>
                <option value="WV">West Virginia</option>
                <option value="WI">Wisconsin</option>
                <option value="WY">Wyoming</option>
            </select>
            <br /><br />
            <div class="row-fluid">
                <table class="easyui-datagrid" title="Basic DataGrid" style="width:700px;height:250px"
                       data-options="singleSelect:true,collapsible:true,url:'http://localhost/projetos/projetoExemploMVC1/public_html/datagrid_data1.json',method:'get'">
                    <thead>
                        <tr>
                            <th data-options="field:'itemid',width:80">Item ID</th>
                            <th data-options="field:'productid',width:100">Product</th>
                            <th data-options="field:'listprice',width:80,align:'right'">List Price</th>
                            <th data-options="field:'unitcost',width:80,align:'right'">Unit Cost</th>
                            <th data-options="field:'attr1',width:250">Attribute</th>
                            <th data-options="field:'status',width:60,align:'center'">Status</th>
                        </tr>
                    </thead>
                </table>
            </div>
        <p>
            <a class="btn" href="#">View details »</a>
        </p>
    </div>

</div> <!-- Fim da div#principal -->
