<?php
$params = $this->getParams();
$config = ($this->getConfigs());
?>
<!-- content -->
<div id="conteudoSMenu">   
    <h3>
        <?php
        echo $params['ativo'];
        ?>
    </h3>
    <?php
    echo "Controlador: " . Application::getControlador() . "<br />";
    echo "Açaõ: " . Application::getAcao();
    ?>
    <p>
        Exemplo de Aplicação com jQuery EasyUI
    </p>
    <br />

    <fieldset class="ui-widget-content ui-corner-all" style="width: 780px;height:auto; padding: 3px;">
        <legend> Dados Disponíveis </legend>
        <div class="classeDiv">
            <div class="box-esquerdo">
                <label for="estados" class="lb2Lado">Dados fixos 1: </label>
                <select id="estados" class="easyui-combobox" name="estados" style="width:240px;">
                    <option value="Green Adult">Green Adult</option>
                    <option value="Tailless">Tailless</option>
                    <option value="With tail">With tail</option>
                    <option value="Adult Female">Adult Female</option>
                    <option value="Adult Male">Adult Male</option>
                    <option value="Diversos">Diversos</option>        
                </select>
            </div>
            <div class="box-direito">
                <label for="cbCategoria" class="lb2Lado-dir">Categoria BD: </label>
                <select id="cbCategoria" class="easyui-combobox" name="cbCategoria" style="width:240px;"
                        data-options="
                        valueField: 'ID',
                        textField: 'DESCRICAO',
                        url:'<?php echo $config->path; ?>apoio/comboboxCategoria'
                        "
                        >       
                </select>
            </div>
        </div>
        <div class="classeDiv">
            <div class="box-esquerdo">
                <label for="cc1" class="lb2Lado">Dados fixos 2: </label>
                <input id="cc1" class="easyui-combobox" style="width:240px;"
                       data-options="
                       valueField: 'id',
                       textField: 'text',
                       url:'<?php echo $config->path; ?>cb_data1.json'
                       ">
            </div>
            <div class="box-direito">
                <label for="cbEstados" class="lb2Lado-dir">Estados: </label>
                <select id="cbEstados" class="easyui-combobox" name="cbEstados" style="width:240px;"
                        data-options="
                        valueField: 'UF',
                        textField: 'NOME',
                        url:'<?php echo $config->path; ?>apoio/comboboxEstado'
                        "
                        >
                    
                </select>
            </div>
        </div>
        <div class="classeDiv">
            <div class="box-esquerdo">
                <label for="status" class="lb2Lado">Status Produtos: </label>
                <select id="status" class="easyui-combobox" name="status" style="width:240px;">
                    <option value="P">Ponta</option>
                    <option value="E">Estoque</option>
                    <option value="F">Falta</option>
                </select>
            </div>
        </div>
    </fieldset>
    <br />
    <div class="row-fluid">
        <table id="dgBasico" class="container easyui-datagrid" title="Exemplo Dados do BD" 
               style="height:280px; width: 788px;"
               data-options="singleSelect:true,
               collapsible:true,
               remoteSort: false,
               url:'<?php echo $config->path; ?>main/dgExemplo',
               fitColumns: false,
               rownumbers: true,
               rowStyler: rowFormater,
               method:'get'
               ">
            <thead>
                <tr>
                    <th data-options="field:'itemid',width:70, align:'center'" formatter="formatAction1" >acoes</th>
                    <th data-options="field:'productid',width:70" sortable="true">Product</th>
                    <th data-options="field:'listprice',width:70,align:'right'" sortable="true">List Price</th>
                    <th data-options="field:'unitcost',width:70,align:'right'" sortable="true">Unit Cost</th>
                    <th data-options="field:'productname',width:180" sortable="true">Product Name</th>
                    <th data-options="field:'descricao',width:100" sortable="true">Attribute</th>
                    <th data-options="field:'status',width:70,align:'center'" sortable="true">Status</th>
                    <th data-options="field:'nome',width:150,align:'center'" sortable="true">Estado</th>
                </tr>
            </thead>
        </table>
    </div>
    <br />
    <a href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-search'" onclick="recarregarDados()">Recarregar</a>
    <a href="javascript:clearFormDados('0626')" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-reload'" >Limpar</a>
    <br /><br />
    <fieldset class="ui-widget-content ui-corner-all" style="width: 780px;height:200px; padding: 3px;">
        <legend>Legend</legend> 
        <div id="format">
            <input type="checkbox" id="check1" /><label for="check1">B</label>
            <input type="checkbox" id="check2" /><label for="check2">I</label>
            <input type="checkbox" id="check3" /><label for="check3">U</label>
        </div>
        <br />
        <form>

            <label>Label name</label>
            <input type="text" class="form-control" placeholder="Email" style="width: 80%">
            <span class="help-block">Example block-level help text here.</span>
            <label class="checkbox"><input type="checkbox"> Check me out</label>
            <button type="submit" class="btn" id="btnSubmit">Submit</button>
    </fieldset>
</form>
<br />        
</div> <!-- Fim da div#principal -->