<?php
$params = $this->getParams();
$config = ($this->getConfigs());
?>
<!-- content -->
<div id="conteudoSMenu">   
    <h3>
        <?php
        echo $params['ativo'];
        ?>
    </h3>
    <?php
    echo "Controlador: " . Application::getControlador() . "<br />";
    echo "Açaõ: " . Application::getAcao();
    ?>
    <p>
        Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. 
        Aliquam eget sapien sapien. Curabitur in metus urna. In hac habitasse platea dictumst. 
        Phasellus eu sem sapien, sed vestibulum velit. Nam purus nibh, lacinia non faucibus et, 
        pharetra in dolor. Sed iaculis posuere diam ut cursus. 
        <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet,
            metus nunc consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna,
        vulputate nec bibendum nec, posuere nec lacus. 
        <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. 
            Nulla euismod ultrices massa, et feugiat ipsum consequat eu.</small>
    </p>
    <br />
    <select id="estados" class="easyui-combobox" name="estados" style="width:200px;">
        <option value="Green Adult">Green Adult</option>
        <option value="Tailless">Tailless</option>
        <option value="With tail">With tail</option>
        <option value="Adult Female">Adult Female</option>
        <option value="Adult Male">Adult Male</option>
        <option value="Diversos">Diversos</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
    </select>
    <br />
    <input id="cc1" class="easyui-combobox" data-options="
           valueField: 'id',
           textField: 'text',
           url:'<?php echo $config->path; ?>cb_data1.json'
           ">

    <span>Status dos Proudos: </span>

    <select id="status" class="easyui-combobox" name="status" style="width:200px;">
        <option value="P">Ponta</option>
        <option value="E">Estoque</option>
        <option value="F">Falta</option>
    </select>
    <br /><br />

    <div class="row-fluid">
        <table id="dgBasico" class="container easyui-datagrid" title="Basic DataGrid" style="height:250px"
               data-options="singleSelect:true,
               collapsible:true,
               remoteSort: false,
               url:'<?php echo $config->path; ?>main/dgExemplo',
               fitColumns: true,
               rownumbers: true,
               rowStyler: rowFormater
               ,method:'get'
               ">
            <thead>
                <tr>
                    <th data-options="field:'itemid',width:90" formatter="formatAction1" >acoes</th>
<!--                    <th data-options="field:'itemid',width:60" sortable="true">Item ID</th>-->
                    <th data-options="field:'productid',width:50" sortable="true">Product</th>
                    <th data-options="field:'listprice',width:60,align:'right'" sortable="true">List Price</th>
                    <th data-options="field:'unitcost',width:60,align:'right'" sortable="true">Unit Cost</th>
                    <th data-options="field:'productname',width:150" sortable="true">Product Name</th>
                    <th data-options="field:'attr1',width:90" sortable="true">Attribute</th>
                    <th data-options="field:'status',width:60,align:'center'" sortable="true">Status</th>
                </tr>
            </thead>
        </table>
    </div>
    <br />
    <a href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-search'" onclick="recarregarDados()">Recarregar</a>
    <a href="javascript:clearFormDados('0626')" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-reload'" >Limpar</a>
    <br /><br /><br />
    <div id="format">
        <input type="checkbox" id="check1" /><label for="check1">B</label>
        <input type="checkbox" id="check2" /><label for="check2">I</label>
        <input type="checkbox" id="check3" /><label for="check3">U</label>
    </div>
    <br />
    <form>
        <fieldset>
            <legend>Legend</legend> 
            <label>Label name</label>
            <input type="text" class="form-control" placeholder="Email">
            <span class="help-block">Example block-level help text here.</span>
            <label class="checkbox"><input type="checkbox"> Check me out</label>
            <button type="submit" class="btn" id="btnSubmit">Submit</button>
        </fieldset>
    </form>
    <br />        
</div> <!-- Fim da div#principal -->