<?php
$params = $this->getParams();
$config = ($this->getConfigs());
$esyui = (!isset($config->theme->easyui)) ? 'default' : $config->theme->easyui;
$esyui = ($esyui == "") ? "default" : $esyui;
?>

<!--CSS - do jQueryUI para o sistema nao mexer -->
<link rel="stylesheet" href="<?php echo $config->path; ?>common/library/jquery-ui-1.9.1/jquery-ui-1.9.1.custom.css" />   
<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/library/jquery-alerts/jquery.alerts.css" />  

<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/library/jquery-easyui-1.4.1/themes/<?php echo $esyui; ?>/easyui.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/library/jquery-easyui-1.4.1/themes/icon.css" />

<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/css/icon.personalizado.css" />

<link href="<?php echo $config->path; ?>common/css/bootstrap.personalizado.css" rel="stylesheet" media="screen" />
<!-- CSS personalizado do seu site -->
<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/css/site.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $config->path; ?>common/css/forms.css" />


<!-- JS plugins e frameworks -->
<script src="<?php echo $config->path; ?>common/library/plugins/jquery-1.8.3.js"></script>  
<script src="<?php echo $config->path; ?>common/library/jquery-ui-1.9.1/jquery-ui-1.9.1.custom.js"></script>
<script src="<?php echo $config->path; ?>common/library/jquery-alerts/jquery.alerts.js"></script>            
<script src="<?php echo $config->path; ?>common/library/plugins/jquery.maskedinput.js"></script>
<script src="<?php echo $config->path; ?>common/library/plugins/jquery.epiclock.min.js"></script>            
<script src="<?php echo $config->path; ?>common/library/jquery-easyui-1.4.1/jquery.easyui.min.js"></script>
<script src="<?php echo $config->path; ?>common/library/jquery-easyui-1.4.1/locale/easyui-lang-pt_BR.js"></script>

<!-- content -->
<div id="principal" class="container">    
    <div class="span12">
        <h3>
            <?php echo $params['ativo']; ?>
        </h3>
        <br />
    </div>
    
    
    <br />
    <select id="estados" class="easyui-combobox" name="estados" style="width:200px;">
        <option value="Green Adult">Green Adult</option>
        <option value="Tailless">Tailless</option>
        <option value="With tail">With tail</option>
        <option value="Adult Female">Adult Female</option>
        <option value="Adult Male">Adult Male</option>
        <option value="Diversos">Diversos</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
    </select>
    <br />
    <input id="cc1" class="easyui-combobox" data-options="
           valueField: 'id',
           textField: 'text',
           url:'<?php echo $config->path; ?>cb_data1.json'
           ">

    <span>Status dos Proudos: </span>

    <select id="status" class="easyui-combobox" name="status" style="width:200px;">
        <option value="P">Ponta</option>
        <option value="E">Estoque</option>
        <option value="F">Falta</option>
    </select>
    <br /><br />
    
    
</div> <!-- Fim da div#principal -->
